gp_platform_home:
    path:      /{page}
    defaults:  { _controller: GPPlatformBundle:Customer:index, page: 1 }
    requirements:
        page: \d*

gp_platform_view:
    path:      /customer/{id}
    defaults:  { _controller: GPPlatformBundle:Customer:view }
    requirements:
        id: \d+

gp_platform_add:
    path:      /add
    defaults:  { _controller: GPPlatformBundle:Customer:add }

gp_platform_edit:
    path:      /edit/{id}
    defaults:  { _controller: GPPlatformBundle:Customer:edit }
    requirements:
        id: \d+

gp_platform_delete:
    path:      /delete/{id}
    defaults:  { _controller: GPPlatformBundle:Customer:delete }
    requirements:
        id: \d+

gp_platform_viewAll:
    path:      /viewAll
    defaults:  { _controller: GPPlatformBundle:Customer:viewAll }

gp_platform_search:
    path:      /search
    defaults:  { _controller: GPPlatformBundle:Customer:search }

gp_platform_uploadImage:
    path:      /uploadImage/{id}
    defaults:  { _controller: GPPlatformBundle:Customer:uploadImage }

gp_platform_addCar:
    path:      /addCar/{id}
    defaults:  { _controller: GPPlatformBundle:Car:add }

gp_platform_editCar:
    path:      /editCar/{id}
    defaults:  { _controller: GPPlatformBundle:Car:edit }

gp_platform_deleteCar:
    path:      /deleteCar/{id}
    defaults:  { _controller: GPPlatformBundle:Car:delete }

gp_platform_addBill:
    path:      /addBill
    defaults:  { _controller: GPPlatformBundle:Bill:add }

gp_platform_viewBills:
    path:      /viewBills
    defaults:  { _controller: GPPlatformBundle:Bill:viewBills }

gp_platform_viewBill:
    path:      /bill/{id}
    defaults:  { _controller: GPPlatformBundle:Bill:viewBill }
    requirements:
        id: \d+

gp_platform_editBill:
    path:      /editBill/{id}
    defaults:  { _controller: GPPlatformBundle:Bill:edit }
    requirements:
        id: \d+

gp_platform_deleteBill:
    path:      /deleteBill/{id}
    defaults:  { _controller: GPPlatformBundle:Bill:delete }
    requirements:
        id: \d+