<?php

namespace GP\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends EntityRepository
{
	//Method who return customers by Name
	public function searchByName($key)
	{
		$qb = $this->createQueryBuilder('a');

  		$qb
    		->where('a.lastname LIKE :key')
			->setParameter('key', $key.'%');
			
  		return $qb
    		->getQuery()
    		->getResult();
	}
	
	//Method to get customers by ASC by LASTNAME
	public function getCustomersByLastnameASC()
	{
		return $this->findBy(array(), array('lastname' => 'ASC'));
	}
}
